version: "3.9"

volumes:
  db-store:

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./infra/development/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - front
      - back

  front:
    container_name: front
    image: node:18.18-alpine3.18
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: sh -c "npm run dev"
    ports:
      - 3000:3000

  back:
    container_name: back
    image: node:18.18-alpine3.18
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: sh -c "npm run start:dev"
    ports:
      - 2000:2000
    depends_on:
      - db

  db:
    image: mongo:7.0.2
    container_name: db
    volumes:
      - db-store:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: fmjp
      MONGO_INITDB_ROOT_PASSWORD: fmjp
